apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_DEBUG: {{ .Values.env.APP_DEBUG | quote }}
  LOG_CHANNEL: {{ .Values.env.LOG_CHANNEL | quote }}
  CACHE_DRIVER: {{ .Values.env.CACHE_DRIVER | quote }}
  SESSION_DRIVER: {{ .Values.env.SESSION_DRIVER | quote }}
  QUEUE_CONNECTION: {{ .Values.env.QUEUE_CONNECTION | quote }}