{{- if .Values.scheduler.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laravel-app.fullname" . }}-scheduler
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: scheduler
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["php", "artisan", "schedule:run"]
              envFrom:
                - configMapRef:
                    name: {{ include "laravel-app.fullname" . }}-config
              env:
                - name: APP_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "laravel-app.fullname" . }}-secret
                      key: APP_KEY
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
{{- end }}